Resources:
    ContentBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: ${self:custom.contentBucketName}
            PublicAccessBlockConfiguration:
                BlockPublicAcls: true
                BlockPublicPolicy: true
                IgnorePublicAcls: true
                RestrictPublicBuckets: true

    ContentBucketPolicy:
        Type: AWS::S3::BucketPolicy
        Properties:
            Bucket: !Ref ContentBucket
            PolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - 
                        Action:
                            - s3:GetObject
                        Effect: Allow
                        Resource: arn:aws:s3:::${self:custom.contentBucketName}/*
                        Principal:
                            AWS: !Sub 
                                    - arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${AccessIdentity}
                                    - AccessIdentity: !Ref ContentAccessIdentity
        DependsOn: ContentAccessIdentity


    # ContentBucketPolicy:
    #     Type: AWS::S3::BucketPolicy
    #     Properties:
    #         Bucket: !Ref ContentBucket
    #         PolicyDocument:
    #             Fn::Join:
    #             - ''
    #             -
    #                 - '{
    #                     "Version": "2012-10-17",
    #                     "Statement": [
    #                     {
    #                         "Sid": "1",
    #                         "Effect": "Allow",
    #                         "Principal": {
    #                         "AWS": "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity '
    #                 - Ref: ContentAccessIdentity
    #                 - '"
    #                         },
    #                         "Action": "s3:GetObject",
    #                         "Resource": "arn:aws:s3:::${self:custom.contentBucketName}'
    #                 - '/*"
    #                     }
    #                     ]
    #                 }'
    #     DependsOn: ContentAccessIdentity