Resources:
    ContentBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: ${self:custom.contentBucketName}
            PublicAccessBlockConfiguration:
                BlockPublicAcls: true
                BlockPublicPolicy: true
                IgnorePublicAcls: true
                RestrictPublicBuckets: true

    ContentBucketPolicy:
        Type: AWS::S3::BucketPolicy
        Properties:
            Bucket: !Ref ContentBucket
            PolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - 
                        Action:
                            - s3:GetObject
                        Effect: Allow
                        Resource: arn:aws:s3:::${self:custom.contentBucketName}/*
                        Principal:
                            AWS: !Sub 
                                    - arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${AccessIdentity}
                                    - AccessIdentity: !Ref ContentAccessIdentity
        DependsOn: ContentAccessIdentity