Resources:             
    ContentCFDistribution:
        Type: AWS::CloudFront::Distribution
        Properties:
            DistributionConfig:
                DefaultCacheBehavior:
                    AllowedMethods:
                        - GET
                        - HEAD
                        - OPTIONS
                    TargetOriginId: S3ContentOrigin
                    CachedMethods:
                        - GET
                        - HEAD
                        - OPTIONS
                    OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf
                    CachePolicyId: b2884449-e4de-46a7-ac36-70bc7f1ddd6d
                    LambdaFunctionAssociations:
                        - 
                            EventType: 'viewer-request'
                            LambdaFunctionARN: PLACEHOLDER
                    ViewerProtocolPolicy: 'redirect-to-https'
                Origins:
                    - DomainName: ${self:custom.contentBucketName}.s3.amazonaws.com
                      Id: S3ContentOrigin
                      S3OriginConfig:
                          OriginAccessIdentity: !Sub
                                                  - origin-access-identity/cloudfront/${Identity}
                                                  - Identity: !Ref ContentAccessIdentity
                Enabled: true
                Comment: S3 content origin
                HttpVersion: http2
                PriceClass: PriceClass_100
                ViewerCertificate:
                    CloudFrontDefaultCertificate: true

    ContentAccessIdentity:
        Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
        Properties:
            CloudFrontOriginAccessIdentityConfig:
                Comment: 'CloudFront to S3 Access Identity'

