Resources:
    ContentAuthorizerRole:
        Type: AWS::IAM::Role
        Properties:
            Path: "/"
            RoleName: ${self:provider.stage}-13125381-content-authorizer-role
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    -   
                        Sid: AllowLambdaServiceToAssumeRole
                        Effect: Allow
                        Action:
                            - sts:AssumeRole
                        Principal:
                            Service:
                                - lambda.amazonaws.com
                                - edgelambda.amazonaws.com
